### ISSUE TITLE
WOOF and WOOF2 files missing with 4.0.0 release

### ISSUE THREAD

**Issue by ChetanGandhi** [google/material-design-icons#1092]
Hi, first of all thanks for creating such a beautiful icon library.

Can you please confirm that support for WOOF and WOOF2 files is dropped with the latest release, 4.0.0 ?

Correct me if I am wrong,
OTF files are full system font file (to be used as desktop operating system font) and not as web font.
Is it ok to, somehow, convert the OTF files to WOOF2 format and use them instead?

Thanks.

**Comment by ytx21cn** [comment]
I am using Ubuntu.

### ttf / otf → woff
The ttf / otf → woff utility is [**woff-tools**](https://packages.ubuntu.com/source/woff-tools).
Conversion command:
```
$ sfnt2woff path/to/otf.otf
```
This will create the woff file in the same directory as the otf file.


### ttf / otf → woff2
The ttf / otf → woff2 utility is [**woff2**](https://packages.ubuntu.com/source/woff2).
```
$ woff2_compress path/to/otf.otf
```
This will create the woff2 file in the same directory as the otf file.



These two utilities provide convenient command-line conversions to the desired formats.

**Comment by ChetanGandhi** [comment]
@ytx21cn Thanks for the details, this will unblock me for now.

Though I will still wait for a official confirmation that support for WOOF/WOOF2 files is dropped. The official documentation still refers to old release and is using WOOF/WOOF2 file. In case next update fixes this, then I will have to refactor my implementation, again.

**Comment by yuvalbl** [comment]
@ChetanGandhi is correct, The docs are out of date. This is from the [official docs](http://google.github.io/material-design-icons/#icon-font-for-the-web)

```
@font-face {
  /*...*/
  src: local('Material Icons'),
    local('MaterialIcons-Regular'),
    url(https://example.com/MaterialIcons-Regular.woff2) format('woff2'),
    url(https://example.com/MaterialIcons-Regular.woff) format('woff'),
    url(https://example.com/MaterialIcons-Regular.ttf) format('truetype');
}
```
But no `woff2`or `woff` included in the repo.
Moreover, link to icon font assets result in 404
![image](https://user-images.githubusercontent.com/11487010/96864495-2f28e000-1471-11eb-8b20-d3f4c519c2a3.png)

**Comment by Download** [comment]
See #1050

**Comment by RoelN** [comment]
Thanks for this issue and the replies, and apologies for the slow updates. Thanks for bearing with us.

We're gathering all feedback and suggestions regarding updating the npm package in a central issue: https://github.com/google/material-design-icons/issues/1129 Please have a look and see if the package, as published in the way suggested there, would suit your needs.

**Comment by zijianhuang** [comment]
The workaround is to follow the links in https://github.com/google/material-design-icons/blob/master/font/README.md

Then browse one of the links you want like:
https://fonts.googleapis.com/css2?family=Material+Icons

Then in the CSS returned, follow the woff2 link, like:
https://fonts.gstatic.com/s/materialicons/v76/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2

Then you get woff2 for local hosting. And you may either keep the hashed name, or rename to something like MaterialIcons-Regular.woff2

**Comment by adamreisnz** [comment]
The workaround does not give you the WOFF file though (woff 1) for older browsers.

**Comment by optyler** [comment]
I needed the regular and outlined fonts, to do so : 
I opened https://fonts.googleapis.com/css?family=Material+Icons%7CMaterial+Icons+Outlined
I went to chrome dev tools, `Cmd+Shift+p` and wrote searched for `Network conditions`. 
I change the user agent for Edge, FF, Chrome, Android, ... 

Here was the condensed css of all those links I could get this way and the CSS. 
Up to you to download the fonts and point to them directly.

I don't know if the orders of urls are important.

```css
/* fallback */
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/materialicons/v118/flUhRq6tzZclQEJ-Vdg-IuiaDsNa.woff) format('woff'),
    url(https://fonts.gstatic.com/s/materialicons/v118/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2) format('woff2'),
    url(https://fonts.gstatic.com/s/materialicons/v118/flUhRq6tzZclQEJ-Vdg-IuiaDsNZ.ttf) format('truetype'),
    url(https://fonts.gstatic.com/s/materialicons/v118/flUhRq6tzZclQEJ-Vdg-IuiaDsNY.eot);
}

/* fallback */
@font-face {
  font-family: 'Material Icons Outlined';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/materialiconsoutlined/v92/gok-H7zzDkdnRel8-DQ6KAXJ69wP1tGnf4ZGhUcel5euIg.woff2) format('woff2'),
        url(https://fonts.gstatic.com/s/materialiconsoutlined/v92/gok-H7zzDkdnRel8-DQ6KAXJ69wP1tGnf4ZGhUcd.otf) format('opentype'),
        url(https://fonts.gstatic.com/s/materialiconsoutlined/v92/gok-H7zzDkdnRel8-DQ6KAXJ69wP1tGnf4ZGhUcY.woff) format('woff'),
        url(https://fonts.gstatic.com/s/materialiconsoutlined/v92/gok-H7zzDkdnRel8-DQ6KAXJ69wP1tGnf4ZGhUca.eot);
}

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}

.material-icons-outlined {
  font-family: 'Material Icons Outlined';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}
```
