### ISSUE TITLE
Incorrect person_off icon from font files

### ISSUE THREAD

**Issue by msherman** [google/material-design-icons#1149]
Issue:
I downloaded the font files from the font folder located in the repo, loaded them in to my web application by defining the font-face and appropriate css. Set the icon to use `person_off` from the font files, and it is currently showing the `person` icon instead.

Font configuration:
```css
@font-face {
	font-family: 'Material Icons';
	font-style: normal;
	font-weight: 400;
	src: local('Material Icons'),
			 local('MaterialIcons-Regular'),
			 url(../assets/material-icons/MaterialIcons-Regular.ttf) format('truetype');
}
.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;  /* Preferred icon size */
  display: inline-block;
  line-height: 1;
  text-transform: none;
  letter-spacing: normal;
  word-wrap: normal;
  white-space: nowrap;
  direction: ltr;

  /* Support for all WebKit browsers. */
  -webkit-font-smoothing: antialiased;
  /* Support for Safari and Chrome. */
  text-rendering: optimizeLegibility;

  /* Support for Firefox. */
  -moz-osx-font-smoothing: grayscale;

  /* Support for IE. */
  font-feature-settings: 'liga';
}
```

font use as icon:
```html
<i class="material-icons">person_off</i>
````
Icons shows as available as part of the material.io resources
https://material.io/resources/icons/?icon=person_off&style=baseline

Icon does not appear in the src code for this repo.
https://github.com/google/material-design-icons/tree/master/src/social
