### ISSUE TITLE
The HTML element generated  on the website doesn't separate the class names

### ISSUE THREAD

**Issue by Cristhian611** [google/material-design-icons#1151]
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>

When you select any of the five icon styles on `https://fonts.google.com/icons`, the HTML element generated doesn't separate the class names, I don't know if it's intentional, but it can be frustrating for a beginner to see it doesn't work the first time.

>**HTML element generated:** 
>
>```html
><span class="material-icons-round">home</span> 
>```

`material-icons-round` ❌

`material-icons round` ✅

**Comment by RoelN** [comment]
The classnames shouldn't be separated. Did that actually work for you?

If you fetch the rounded font via `https://fonts.googleapis.com/icon?family=Material+Icons+Round`, this is the CSS that gets returned:

``` css
/* fallback */
@font-face {
  font-family: 'Material Icons Round';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/materialiconsround/v49/LDItaoyNOAY6Uewc665JcIzCKsKc_M9flwmPq_HTTw.woff2) format('woff2');
}

.material-icons-round {
  font-family: 'Material Icons Round';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -moz-font-feature-settings: 'liga';
  -moz-osx-font-smoothing: grayscale;
}
```

Which is using the `material-icons-round` classname.

I'm closing this as this matches the instructions https://fonts.google.com/icons, but feel free to reopen with more details if you still think this is a bug!
