### ISSUE TITLE
Icons from Google Fonts do not work inside Web Components (ShadowDOM?)

### ISSUE THREAD

**Issue by krhoyt** [google/material-design-icons#1165]
Using the Material Icons from Google Fonts with a ```link``` tag in ```index.html```. Placing a ```<span class="material-icons">face</span>``` in the ```index.html``` works as expected. When I put that same markup inside a Web Component, the icon is not rendered, but rather the word "face". I have tried putting the markup in my template directly, as well as compose the content via ```slot```. Neither renders the icon. Note that other fonts from Google Fonts (such as Roboto) function as expected.

**Comment by haifax4** [comment]
https://github.com/google/material-design-icons/issues/1165#issue-846909010

**Comment by ershov** [comment]
Same here

**Comment by ershov** [comment]
Ok I was able to get a workaround for this.
You need to specify the css link in both root document and shadow dom, then it works.
Looks like a bug in Chrome.

**Comment by jfbrennan** [comment]
@krhoyt if @ershov 's suggestion worked, you might want to close this issue to reduce noise in the backlog

**Comment by epavanello** [comment]
> Ok I was able to get a workaround for this. You need to specify the css link in both root document and shadow dom, then it works. Looks like a bug in Chrome.

This works because shadow dom need outside defined fonts, but material icons needs inner class .material-icons defined to map the outside font to the local span.

Another optimization/workaround is to include fonts in the documents and define inside shadow dom only the utility class
`
.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-smoothing: antialiased;
}`

**Comment by tphinney** [comment]
Looks like this is all sorted out.

**Comment by sifullahshakh** [comment]
thank u so much

**Comment by jfbrennan** [comment]
FWIW, if anyone comes here looking to do Material Symbols as a Web Component, it requires shockingly little code:
```css
/* Define the icon font */
@font-face {
  font-family: 'x-icons';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/materialsymbolsoutlined/v134/kJF4BvYX7BgnkSrUwT8OhrdQw4oELdPIeeII9v6oDMzBwG-RpA6RzaxHMPdY40KH8nGzv3fzfVJU22ZZLsYEpzC_1ver5Y0J1Llf.woff2) format('woff2');
}

/* Define a custom icon tag */
x-icon::before {
  font-family: 'x-icons';
  content: attr(name);
  -webkit-font-smoothing: antialiased;
}

/* Filled variation */
x-icon[fill]::before {
  font-variation-settings: 'FILL' 1;
}
```
Then anywhere you can render HTML, simply do:
```html
<x-icon name="person"></x-icon>
<x-icon name="person" fill></x-icon>
```
No actual Custom Element needs to be defined. Add ARIA as needed and customize the size, color, etc.
