### ISSUE TITLE
Add visibility property to the webfont CSS

### ISSUE THREAD

**Issue by albertorestifo** [google/material-design-icons#127]
I normally load the web font asynchronously. If I use `display: none`, once the icons load I will have a change in layout.

Instead, I normally use the following CSS directly in the header:

```css
.material-icons {
  visibility: hidden;
  height: 24px;
  width: 25px;
}
```

That way, once the web-font css is loaded, the icons will fill the empty space.
Inserting the property `visibility: visible` would allow to avoid the use of JavaScript to remove the `visibility: hidden` property once the web-font loads, as it will simply be overwritten.
