### ISSUE TITLE
word-wrap:break-word on parent elements break webfont

### ISSUE THREAD

**Issue by mydudechris** [google/material-design-icons#141]
Might be worth adding this

````css
.material-icons {
  word-wrap: normal;
}
````

if a parent element, like body, is set to break-word then the webfont doesn't work properly.
