### ISSUE TITLE
 How to use fill variation in flutter?

### ISSUE THREAD

**Issue by jessicamrbr** [google/material-design-icons#1543]
Could anyone help me how can I use fill variant when using font in flutter?

```yaml
  fonts:
    - family: MaterialSymbols
      fonts:
        - asset: lib/utils/assets/fonts/MaterialSymbolsRounded.ttf
          weight: 400
``` 

```dart
Text(
  "\ue131", 
  style: TextStyle(
    fontFamily: "MaterialSymbols",
  ),
);
```

**Comment by tphinney** [comment]
https://developers.google.com/fonts/docs/material_symbols

basically you want:

`font-variation-settings: 'fill' 1;`

**Comment by jessicamrbr** [comment]
It worked!

I suggest changing the CSS tag to Dart or Flutter.

```yaml
  fonts:
    - family: MaterialSymbols
      fonts:
        - asset: lib/utils/assets/fonts/MaterialSymbolsRounded.ttf
          weight: 400
``` 

```dart
Text(
  "\ue131", 
  style: TextStyle(
    fontFamily: "MaterialSymbols",
    fontVariations: const [
      FontVariation('FILL', 1),
    ],
  ),
);
```
