### ISSUE TITLE
Self-Hosted Material Icon Not Showing On Both Chrome and IE

### ISSUE THREAD

**Issue by jig9** [google/material-design-icons#205]
I referred to this link http://google.github.io/material-design-icons/#getting-icons 

@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(https://example.com/MaterialIcons-Regular.eot); /* For IE6-8 */
  src: local('Material Icons'),
       local('MaterialIcons-Regular'),
       url(https://example.com/MaterialIcons-Regular.woff2) format('woff2'),
       url(https://example.com/MaterialIcons-Regular.woff) format('woff'),
       url(https://example.com/MaterialIcons-Regular.ttf) format('truetype');
}

@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(https://example.com/MaterialIcons-Regular.eot); /* For IE6-8 */
  src: local('Material Icons'),
       local('MaterialIcons-Regular'),
       url(https://example.com/MaterialIcons-Regular.woff2) format('woff2'),
       url(https://example.com/MaterialIcons-Regular.woff) format('woff'),
       url(https://example.com/MaterialIcons-Regular.ttf) format('truetype');
}

I replaced the url with the location of the material design icons folder but it won't show up.
Using the link to the Google Web Font, it works perfectly
I used the svg version and it works perfectly too.

**Comment by sachin8080** [comment]
I also did the same and am facing the same issue.

**Comment by shyndman** [comment]
Did you also include the CSS class?
```css
.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;  /* Preferred icon size */
  display: inline-block;
  width: 1em;
  height: 1em;
  line-height: 1;
  text-transform: none;
  letter-spacing: normal;
  word-wrap: normal;
  white-space: nowrap;
  direction: ltr;

  /* Support for all WebKit browsers. */
  -webkit-font-smoothing: antialiased;
  /* Support for Safari and Chrome. */
  text-rendering: optimizeLegibility;

  /* Support for Firefox. */
  -moz-osx-font-smoothing: grayscale;

  /* Support for IE. */
  font-feature-settings: 'liga';
}
```

**Comment by matrix818181** [comment]
Got the same issue on my side. I did compare what I get from using the font locally to using Google Font, in Chrome, I got the same CSS from the inspector.

**Comment by JohanMa4** [comment]
Hi i fix this problem with the next steps:
1. I go to: https://fonts.googleapis.com/icon?family=Material+Icons
2. Copy the content of that page to my custom style sheet.
3. In the @font-face exist a property called url(http://.../.../)
4. Download the font that appear in that property, it should be like this: https://fonts.gstatic.com/s/materialicons/v8/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2

5. Rename the file downloaded and copy in my font folder, and write the route in my style sheet in that @font-face property.

And this is done!

That work to me.

Greeting, i hope that can help in this post.

**Comment by aaronprojects** [comment]
Discovered the same issue... drives me crazy!

Thx @JohanMa4! This is the only solution that works for now...

**Comment by shyndman** [comment]
Hi there,

I put together this little demo that mimics self-hosting. Would you mind using it to confirm the problem?

http://codepen.io/shyndman/pen/GpYJBd?editors=110

And I assume all of you are running Windows? I'm getting a VM going right now to take a look.

**Comment by shyndman** [comment]
Copied details from the dupe bug:

@Tusiji wrote:
I'm try to self host the iconfont(http://google.github.io/material-design-icons/) , but its not work. The chrome console shows that:
```
Failed to decode downloaded font: file:///Users/Pan/Documents/Dev/MDL/Hiar/font/MaterialIcons-Regular.woff2
index.html:1 OTS parsing error: invalid version tag
index.html:1 Failed to decode downloaded font: file:///Users/Pan/Documents/Dev/MDL/Hiar/font/MaterialIcons-Regular.woff
index.html:1 OTS parsing error: invalid version tag
index.html:1 Failed to decode downloaded font: file:///Users/Pan/Documents/Dev/MDL/Hiar/font/MaterialIcons-Regular.ttf
index.html:1 OTS parsing error: invalid version tag
```

**Comment by shyndman** [comment]
Hey,

In the 2.1 release I built the fonts slightly differently. Could you please try again?

**Comment by Tusiji** [comment]
Thx :)

2015-11-18 11:34 GMT+08:00 Scott Hyndman <notifications@github.com>:

**Comment by shyndman** [comment]
Does it work?

**Comment by JohanMa4** [comment]
Hi @shyndman maybe the problem to run materialize icons self-hosted is that some of those files (woff2, woff, ttf) need some decode by another library, if you use my suggestion above maybe materialize icons works fine.

Please look at my suggestion and see how the materialize team load they fonts self-hosted.

I hope it has helped you.

Regards.

**Comment by shyndman** [comment]
Hey @JohanMa4,

No additional decoding required. These formats are native to browsers. 

Are you sure it isn't a font loader they're using so they can get callbacks in JavaScript?

**Comment by JohanMa4** [comment]
I think that maybe they use some JavaScripts callbacks.
And if you see my suggestion you can look that they only load one font type .woff2.

I think too that the fonts version are outdated.

**Comment by shyndman** [comment]
Google Fonts serves browser-specific CSS. If you're using Chrome, they'll serve woff2. Safari? woff. Something older? ttf.

The self-hosting CSS was written with input from the Fonts team, so it should work great.

**Comment by JohanMa4** [comment]
@shyndman reading this post: http://stackoverflow.com/questions/30442319/failed-to-decode-downloaded-font maybe you can see the problem.

As it says there, the problem is for bad url format to call the fonts in the css.

I hope it has helped you.

**Comment by Wifsimster** [comment]
I'm having the same issues here in latest Chrome/Firefox stable.
Self-hosting doesn't worked, only solution is to download woff2 from https://fonts.gstatic.com/s/materialicons/v8/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2 like @JohanMa4 said.

**Comment by MacgyverMartins** [comment]
Same problem here.
It's work if I use:
```css
      @font-face {
        font-family: 'Material Icons';
        font-style: normal;
        font-weight: 400;
        src: url(MaterialIcons-Regular.eot); /* For IE6-8 */
        src: local('Material Icons'),
             local('MaterialIcons-Regular'),
             url(https://rawgit.com/google/material-design-icons/master/iconfont/MaterialIcons-Regular.woff2) format('woff2'),
             url(https://rawgit.com/google/material-design-icons/master/iconfont/MaterialIcons-Regular.woff) format('woff'),
             url(https://rawgit.com/google/material-design-icons/master/iconfont/MaterialIcons-Regular.ttf) format('truetype');
      }
```

but if I use self-hosting I hade this messages in Chrome (MacOS)
```
roboto-black-webfont.eot:1 Failed to decode downloaded font: http://localhost:3333/fonts/material-design-icons/iconfont/MaterialIcons-Regular.woff2
roboto-black-webfont.eot:1 OTS parsing error: invalid version tag
roboto-black-webfont.eot:1 Failed to decode downloaded font: http://localhost:3333/fonts/material-design-icons/iconfont/MaterialIcons-Regular.woff
roboto-black-webfont.eot:1 OTS parsing error: invalid version tag
roboto-black-webfont.eot:1 Failed to decode downloaded font: http://localhost:3333/fonts/material-design-icons/iconfont/MaterialIcons-Regular.ttf
roboto-black-webfont.eot:1 OTS parsing error: invalid version tag
```
