### ISSUE TITLE
Stylesheet inconsistent with hosted version

### ISSUE THREAD

**Issue by Zodiase** [google/material-design-icons#299]
The hosted version at https://fonts.googleapis.com/icon?family=Material+Icons doesn't define `width` and `height` while both the stylesheet in this repo and on http://google.github.io/material-design-icons/#icon-font-for-the-web define `width` and `height` to be `1em`.

With the size specified, it breaks the "two-line" example in http://www.getmdl.io/components/index.html#lists-section.

See demo live here: https://codepen.io/Zodiase/pen/yeqoPe/left/.

I'm not sure if it's MDL not correctly handling the latest css code, or you were not supposed to do that. My problem here is that I'm using the stylesheet from here with MDL and it's impossible for me to switch to the hosted version.

**Comment by Zodiase** [comment]
@Garbee Would you please also take a look at this?

**Comment by Garbee** [comment]
This is up to the team for this repository to deal with. I don't know what their purpose for the differences is.

**Comment by Zodiase** [comment]
@Garbee Thanks for the input. I'm just not sure who's maintaining the hosted version on Google fonts. If the changes here got pushed to there, then this difference will be affecting all MDL v1.1.0 users and the CSS code for the List component will have to be updated/fixed accordingly, right?

**Comment by Garbee** [comment]
Lists are already undergoing an update for 1.1.1. However, that isn't relevant to this repository. Nor is anything MDL related. This repo is only about the *Icons* provided by the icon team.

If you have an issue with MDL alignment, file that with MDL. If you have an issue with the font CSS or the icons individually in some way, file that here. Please don't try to mix the two because that makes things confusing and harder to figure out what you mean needs addressing.

**Comment by Zodiase** [comment]
@Garbee Sorry for the confusion but I'm not trying to mix two issues together.
I only want to know why this difference exists and if the difference is going to be eliminated, who's leading the changes.
Clearly in this page http://google.github.io/material-design-icons/#icon-font-for-the-web it's saying
```HTML
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```
is equivalent to the following CSS (which is the version in this repo).
```CSS
.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;  /* Preferred icon size */
  display: inline-block;
  width: 1em;
  height: 1em;
  line-height: 1;
  text-transform: none;
  letter-spacing: normal;
  word-wrap: normal;
  white-space: nowrap;
  direction: ltr;

  /* Support for all WebKit browsers. */
  -webkit-font-smoothing: antialiased;
  /* Support for Safari and Chrome. */
  text-rendering: optimizeLegibility;

  /* Support for Firefox. */
  -moz-osx-font-smoothing: grayscale;

  /* Support for IE. */
  font-feature-settings: 'liga';
}
```

This obviously isn't the case. To me I can think of two cases and I'm not sure which one is right.
  1. Another team is maintaining the font CSS and this repo has the wrong CSS,
  2. or this repo is maintaining the font CSS and https://fonts.googleapis.com/icon?family=Material+Icons is outdated.

Depending on which case it is, I have to change my strategy in patching MDL (in my project) in order to use this repo.
And if it's the second case, I thought the MDL team might need to prepare for the change so I asked you to take look at this. But now I think I'll just wait for the feedback from this repo. Thanks @Garbee.

**Comment by cah-ricksuggs** [comment]
I ran into this problem as well, I'm trying to switch to the hosted cdn version of the font, to improve build times, but some of the css properties are missing from the cdn verison.

**Comment by Garbee** [comment]
Can someone provide a *diff* of what is different? If you download our ZIP or use the CDN then each should provide the exact same experience (since they are the same code.)

**Comment by addyosmani** [comment]
@jestelle do you know who the right person to ping about the hosted version of the fonts is?

**Comment by cah-ricksuggs** [comment]
This is the css served by the cdn:

```css
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: local('Material Icons'), local('MaterialIcons-Regular'), url(https://fonts.gstatic.com/s/materialicons/v13/2fcrYFNaTjcS6g4U3t-Y5UEw0lE80llgEseQY3FEmqw.woff2) format('woff2');
}

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}
```

While this is the code included in the `bower install` (https://github.com/google/material-design-icons/blob/master/iconfont/material-icons.css):

```css
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(MaterialIcons-Regular.eot); /* For IE6-8 */
  src: local('Material Icons'),
       local('MaterialIcons-Regular'),
       url(MaterialIcons-Regular.woff2) format('woff2'),
       url(MaterialIcons-Regular.woff) format('woff'),
       url(MaterialIcons-Regular.ttf) format('truetype');
}

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;  /* Preferred icon size */
  display: inline-block;
  width: 1em;
  height: 1em;
  line-height: 1;
  text-transform: none;
  letter-spacing: normal;
  word-wrap: normal;
  white-space: nowrap;
  direction: ltr;

  /* Support for all WebKit browsers. */
  -webkit-font-smoothing: antialiased;
  /* Support for Safari and Chrome. */
  text-rendering: optimizeLegibility;

  /* Support for Firefox. */
  -moz-osx-font-smoothing: grayscale;

  /* Support for IE. */
  font-feature-settings: 'liga';
}
```
