### ISSUE TITLE
Are the new themes of icons available on Google Fonts?

### ISSUE THREAD

**Issue by TangSteven** [google/material-design-icons#773]
Recently four new themes of icons are available: outlined, rounded, two tone, and sharp. Are these available on Google fonts? If not is there a timeline on when they will be added? Thanks.

**Comment by smileytechguy** [comment]
Please this!  With the introduction of themes themes are now required in order to use the outlined version of several important icons, such as `grade`.  I'd like most if a class could be added to change the theme, however, adding a prefix/suffix would be great too!

**Comment by ahlechandre** [comment]
Maybe with modifiers:

```html
<i class="material-icons">dashboard</i>

<i class="material-icons material-icons--outline">dashboard</i>
```

**Comment by smileytechguy** [comment]
@ahlechandre Looks good!  For the CSS from google fonts, it shouldn't be too hard.  Just like:

```css
/* Default from https://fonts.googleapis.com/css?family=Material+Icons */
.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}

/* Added */
.material-icons.material-icons--outline {
  font-family: 'Material Icons Outline';
}
```

Shouldn't be a complex change, would just need to server multiple fonts.
